services:
  api-service:
    container_name: quick-order-container
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9090:8080"
    networks:
      - quick-order-network

networks:
  quick-order-network:
    driver: bridge
