server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://172.25.0.1:5432}/${DB_NAME:java_course}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
openapi:
  service:
    groupName: api-service
    description: This is a mock service for Quick Order API
    title: ${API_TITLE:Quick Order API}
    version: 1.0.0
    serverUrl: http://localhost:${server.port}
    serverName: Quick Order API
