server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
openapi:
  service:
    groupName: api-service
    description: This is a mock service for Quick Order API
    title: Quick Order API
    version: 1.0.0
    serverUrl: http://localhost:{server.port}
    serverName: Quick Order API
