server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://172.25.0.1:5432/java_course
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
# OpenAPI configuration for your service
openapi:
  service:
    groupName: api-service
    description: This is a mock service for Quick Order API
    title: ${API_TITLE:Quick Order API}
    version: 1.0.0
    serverUrl: http://localhost:${server.port}
    serverName: Quick Order API

